# Generated by Django 5.1.2 on 2024-10-30 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discounted_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('SKU', models.CharField(max_length=50, unique=True)),
                ('stock', models.IntegerField()),
                ('rating', models.FloatField()),
                ('reviews_count', models.IntegerField()),
                ('in_stock', models.BooleanField(default=True)),
                ('is_new', models.BooleanField(default=False)),
                ('is_on_sale', models.BooleanField(default=False)),
                ('available_colors', models.JSONField()),
                ('available_sizes', models.JSONField()),
                ('product_type', models.CharField(max_length=50)),
                ('collection', models.CharField(max_length=100)),
                ('main_image', models.ImageField(upload_to='product_images/')),
                ('gallery_images', models.JSONField(blank=True, null=True)),
                ('discount_percentage', models.IntegerField(blank=True, null=True)),
                ('limited_stock_message', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
