# Generated by Django 5.1.2 on 2024-10-30 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_productimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='gallery_images',
        ),
    ]
