# Generated by Django 5.1.2 on 2024-10-31 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_product_gallery_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='Null', unique=True),
            preserve_default=False,
        ),
    ]
