# Generated by Django 5.1.2 on 2024-11-12 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_sliderimages_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sliderimages',
            name='subtitle',
            field=models.CharField(blank=True, max_length=400),
        ),
    ]
