# Generated by Django 5.1.2 on 2024-11-17 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_productimage_big_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='big_images',
        ),
        migrations.CreateModel(
            name='ProductBigImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product_big_images/')),
                ('alt_text', models.CharField(blank=True, max_length=255, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='big_images', to='app.product')),
            ],
        ),
    ]
