# Generated by Django 5.1.2 on 2024-11-17 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_remove_productimage_big_images_productbigimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='productbigimage',
            name='height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productbigimage',
            name='width',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
