# Generated by Django 5.1.2 on 2024-11-18 14:56

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_productbigimage_height_productbigimage_width'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductQueryAsk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=150)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('message', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
