# Generated by Django 5.1.2 on 2024-11-24 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_cartitem_color_cartitem_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='session_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='color',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='app.color'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='size',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='app.size'),
            preserve_default=False,
        ),
    ]
