# Generated by Django 5.1.2 on 2024-12-24 12:03

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_cart_note_cart_terms_agreed_alter_product_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(max_length=100)),
                ('telephone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('company', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(max_length=500)),
                ('apartment', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(max_length=200)),
                ('post_code', models.IntegerField(blank=True, null=True)),
                ('country', models.CharField(max_length=200)),
                ('state', models.CharField(blank=True, max_length=200, null=True)),
                ('order_notes', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
