# Generated by Django 5.1.2 on 2024-12-24 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_checkout'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardname', models.CharField(max_length=100)),
                ('cardtype', models.PositiveSmallIntegerField(choices=[(1, 'American Express'), (2, 'Visa Card'), (3, 'Master Card'), (4, 'Discover Card')])),
                ('cardno', models.CharField(max_length=16)),
                ('cvv', models.CharField(max_length=3)),
                ('exdate', models.DateField()),
            ],
        ),
    ]
